*  Total Patients = DISTINCTCOUNT('public patient_visits'[patient_id])

* Churned Customers = CALCULATE
                      (DISTINCTCOUNT('public patient_visits'[patient_id]),Query1[is_churn] =1)

* Churn Rate % = DIVIDE([Churned Patients],[Total Patients])*100


